# Generated by Django 4.2.27 on 2026-02-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('super_admin', '超级管理员'), ('leader', '院领导'), ('secretary', '行政秘书'), ('logistics', '教职工'), ('counselor', '辅导员'), ('teacher', '任课教师'), ('student', '学生')], max_length=20, verbose_name='角色类型'),
        ),
    ]
