# Generated by Django 4.2.27 on 2026-02-27 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbac', '0003_alter_role_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('staff', '职工')], max_length=20, verbose_name='角色类型'),
        ),
        migrations.CreateModel(
            name='UserPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_code', models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('secretary', '教学秘书'), ('dean', '院长/系主任'), ('secretary_party', '书记'), ('clerk', '干事/科员'), ('section_chief', '科长'), ('deputy_director', '副处长'), ('director', '处长'), ('deputy_bureau', '副厅长'), ('bureau_chief', '厅长')], max_length=30, verbose_name='职务编码')),
                ('is_main', models.BooleanField(default=False, verbose_name='是否主职务')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_holders', to='rbac.department', verbose_name='所属部门')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_positions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户职务',
                'verbose_name_plural': '用户职务',
                'db_table': 'user_positions',
                'ordering': ['-is_main', 'id'],
            },
        ),
    ]
