# Generated by Django 4.2.27 on 2026-02-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_alter_role_role_type_userposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('admin', '管理员'), ('student', '学生'), ('teacher', '教师'), ('staff', '职工')], max_length=20, verbose_name='角色类型'),
        ),
    ]
