# Generated by Django 6.0.1 on 2026-01-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalStatusRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('masses', '群众'), ('member', '团员'), ('activist', '入党积极分子'), ('probationary', '预备党员'), ('party_member', '正式党员')], max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(choices=[('masses', '群众'), ('member', '团员'), ('activist', '入党积极分子'), ('probationary', '预备党员'), ('party_member', '正式党员')], max_length=20, verbose_name='目标状态')),
                ('application_date', models.DateField(verbose_name='申请日期')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='批准日期')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审批状态')),
                ('application_file', models.FileField(blank=True, null=True, upload_to='students/political/', verbose_name='申请书')),
                ('thought_report', models.FileField(blank=True, null=True, upload_to='students/political/', verbose_name='思想汇报')),
                ('other_materials', models.JSONField(blank=True, default=list, verbose_name='其他材料')),
                ('approval_comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '政治面貌流转记录',
                'verbose_name_plural': '政治面貌流转记录',
                'db_table': 'political_status_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name='学号')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('class_name', models.CharField(max_length=50, verbose_name='班级')),
                ('grade', models.CharField(max_length=10, verbose_name='年级')),
                ('political_status', models.CharField(choices=[('masses', '群众'), ('member', '团员'), ('activist', '入党积极分子'), ('probationary', '预备党员'), ('party_member', '正式党员')], default='masses', max_length=20, verbose_name='政治面貌')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='照片')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学生档案',
                'verbose_name_plural': '学生档案',
                'db_table': 'students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('award', '获奖记录'), ('punishment', '惩处记录'), ('research', '科研成果'), ('poverty', '贫困生认定'), ('activity', '活动参与'), ('other', '其他')], max_length=20, verbose_name='记录类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('record_data', models.JSONField(blank=True, default=dict, verbose_name='记录数据')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学生档案记录',
                'verbose_name_plural': '学生档案记录',
                'db_table': 'student_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
