# Generated by Django 6.0.1 on 2026-01-15 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('enrolled', '入学'), ('transfer_in', '转入'), ('transfer_out', '转出'), ('suspend', '休学'), ('resume', '复学'), ('withdraw', '退学'), ('graduate', '毕业'), ('other', '其他')], max_length=20, verbose_name='变动类型')),
                ('from_status', models.CharField(blank=True, max_length=50, verbose_name='变动前状态')),
                ('to_status', models.CharField(max_length=50, verbose_name='变动后状态')),
                ('reason', models.TextField(verbose_name='变动原因')),
                ('change_date', models.DateField(verbose_name='变动日期')),
                ('document_no', models.CharField(blank=True, max_length=100, verbose_name='文件编号')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='students.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学籍变动记录',
                'verbose_name_plural': '学籍变动记录',
                'db_table': 'student_status_changes',
                'ordering': ['-change_date', '-created_at'],
            },
        ),
    ]
