# Generated by Django 4.2.27 on 2026-02-14 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rbac', '0002_initial'),
        ('students', '0003_studentstatuschange'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='counselor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counseling_students', to=settings.AUTH_USER_MODEL, verbose_name='辅导员'),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='rbac.department', verbose_name='学院/部门'),
        ),
    ]
