# Generated by Django 4.2.27 on 2026-02-27 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0004_student_counselor_student_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='查阅原因')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='查阅时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='students.student', verbose_name='被查阅学生')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_view_history', to=settings.AUTH_USER_MODEL, verbose_name='查阅人')),
            ],
            options={
                'verbose_name': '档案查阅日志',
                'verbose_name_plural': '档案查阅日志',
                'db_table': 'archive_view_logs',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
