# Generated by Django 6.0.1 on 2026-01-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='资源名称')),
                ('resource_type', models.CharField(choices=[('meeting_room', '会议室'), ('lecture_hall', '学术报告厅'), ('laboratory', '实验室'), ('classroom', '教室'), ('other', '其他')], max_length=20, verbose_name='资源类型')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='位置')),
                ('capacity', models.IntegerField(default=0, verbose_name='容纳人数')),
                ('equipment', models.JSONField(blank=True, default=list, verbose_name='设备配置')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='图片列表')),
                ('advance_booking_days', models.IntegerField(default=30, verbose_name='提前预约天数')),
                ('min_booking_hours', models.DecimalField(decimal_places=1, default=0.5, max_digits=3, verbose_name='最小预约时长（小时）')),
                ('max_booking_hours', models.DecimalField(decimal_places=1, default=8.0, max_digits=4, verbose_name='最大预约时长（小时）')),
                ('require_approval', models.BooleanField(default=True, verbose_name='需要审批')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
                'db_table': 'resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='预约标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回'), ('cancelled', '已取消'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('approval_comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('approval_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('contact_name', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资源预约',
                'verbose_name_plural': '资源预约',
                'db_table': 'resource_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '资源分类',
                'verbose_name_plural': '资源分类',
                'db_table': 'resource_categories',
                'ordering': ['order', 'id'],
            },
        ),
    ]
