# Generated by Django 4.2.27 on 2026-02-27 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_alter_role_role_type'),
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='rbac.department', verbose_name='归属部门'),
        ),
    ]
