# Generated by Django 4.2.27 on 2026-02-27 14:46

import apps.notifications.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('notification_type', models.CharField(choices=[('all', '全员通知'), ('role', '按角色'), ('department', '按部门'), ('specific', '指定人员')], default='specific', max_length=20, verbose_name='通知类型')),
                ('recipient_roles', models.JSONField(blank=True, default=list, verbose_name='接收角色')),
                ('recipient_departments', models.JSONField(blank=True, default=list, verbose_name='接收部门')),
                ('priority', models.CharField(choices=[('normal', '普通'), ('important', '重要'), ('urgent', '紧急')], default='normal', max_length=20, verbose_name='重要等级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('sent', '已发送'), ('recalled', '已撤回'), ('deleted', '已删除')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('recalled_at', models.DateTimeField(blank=True, null=True, verbose_name='撤回时间')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='总接收人数')),
                ('read_count', models.PositiveIntegerField(default=0, verbose_name='已读人数')),
                ('recipients', models.ManyToManyField(blank=True, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.notifications.models.notification_attachment_path, verbose_name='文件')),
                ('filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='文件类型')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notifications.notification', verbose_name='通知')),
            ],
            options={
                'verbose_name': '通知附件',
                'verbose_name_plural': '通知附件',
                'db_table': 'notification_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('read_device', models.CharField(blank=True, max_length=50, verbose_name='阅读设备')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_records', to='notifications.notification', verbose_name='通知')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '通知阅读记录',
                'verbose_name_plural': '通知阅读记录',
                'db_table': 'notification_reads',
                'ordering': ['-created_at'],
                'unique_together': {('notification', 'user')},
            },
        ),
    ]
