# Generated by Django 4.2.27 on 2026-02-27 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_enabled', models.BooleanField(default=True, verbose_name='流程审批通知')),
                ('file_enabled', models.BooleanField(default=True, verbose_name='文件签章通知')),
                ('academic_enabled', models.BooleanField(default=True, verbose_name='教务通知')),
                ('warning_enabled', models.BooleanField(default=True, verbose_name='预警提醒')),
                ('activity_enabled', models.BooleanField(default=True, verbose_name='活动通知')),
                ('repair_enabled', models.BooleanField(default=True, verbose_name='报修服务通知')),
                ('resource_enabled', models.BooleanField(default=True, verbose_name='资源预约通知')),
                ('award_enabled', models.BooleanField(default=True, verbose_name='评奖评优通知')),
                ('career_enabled', models.BooleanField(default=True, verbose_name='就业服务通知')),
                ('party_enabled', models.BooleanField(default=True, verbose_name='党建团建通知')),
                ('research_enabled', models.BooleanField(default=True, verbose_name='科研管理通知')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='邮件通知')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='短信通知')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='推送通知')),
                ('dnd_enabled', models.BooleanField(default=False, verbose_name='免打扰模式')),
                ('dnd_start_time', models.TimeField(blank=True, null=True, verbose_name='免打扰开始时间')),
                ('dnd_end_time', models.TimeField(blank=True, null=True, verbose_name='免打扰结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '通知设置',
                'verbose_name_plural': '通知设置',
                'db_table': 'notification_settings',
            },
        ),
        migrations.AlterModelOptions(
            name='notificationattachment',
            options={'verbose_name': '通知附件', 'verbose_name_plural': '通知附件'},
        ),
        migrations.RemoveField(
            model_name='notificationattachment',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='notificationattachment',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_status',
            field=models.CharField(default='pending', max_length=20, verbose_name='处理状态'),
        ),
        migrations.AddField(
            model_name='notification',
            name='business_action',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='业务动作'),
        ),
        migrations.AddField(
            model_name='notification',
            name='business_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='业务ID'),
        ),
        migrations.AddField(
            model_name='notification',
            name='business_model',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='业务模型'),
        ),
        migrations.AddField(
            model_name='notification',
            name='business_type',
            field=models.CharField(choices=[('system', '系统通知'), ('workflow', '流程审批'), ('file', '文件签章'), ('academic', '教务通知'), ('warning', '预警提醒'), ('activity', '活动通知'), ('repair', '报修服务'), ('resource', '资源预约'), ('award', '评奖评优'), ('career', '就业服务'), ('party', '党建团建'), ('research', '科研管理')], default='system', max_length=20, verbose_name='业务类型'),
        ),
        migrations.AddField(
            model_name='notification',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='过期时间'),
        ),
        migrations.AddField(
            model_name='notification',
            name='link_params',
            field=models.JSONField(blank=True, default=dict, verbose_name='链接参数'),
        ),
        migrations.AddField(
            model_name='notification',
            name='link_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='跳转链接'),
        ),
        migrations.AddField(
            model_name='notification',
            name='need_action',
            field=models.BooleanField(default=False, verbose_name='需要处理'),
        ),
        migrations.AddField(
            model_name='notificationattachment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='notificationread',
            name='handled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理时间'),
        ),
        migrations.AddField(
            model_name='notificationread',
            name='is_handled',
            field=models.BooleanField(default=False, verbose_name='是否已处理'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['business_type', 'created_at'], name='notificatio_busines_f8c3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sender', 'created_at'], name='notificatio_sender__27efc9_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'created_at'], name='notificatio_status_dee16f_idx'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_setting', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
