# Generated by Django 4.2.27 on 2026-02-27 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_notificationsetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建通知'), ('send', '发送通知'), ('recall', '撤回通知'), ('delete', '删除通知'), ('update', '更新通知'), ('mark_as_read', '标记已读'), ('mark_as_handled', '标记已处理'), ('batch_mark_read', '批量标记已读'), ('upload_attachment', '上传附件'), ('download_attachment', '下载附件'), ('delete_attachment', '删除附件'), ('view_detail', '查看详情'), ('view_stats', '查看统计'), ('update_settings', '更新设置'), ('suspicious', '可疑活动'), ('rate_limit', '频率限制'), ('security_alert', '安全警告')], max_length=30, verbose_name='操作类型')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='详细信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification', verbose_name='通知')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '通知操作日志',
                'verbose_name_plural': '通知操作日志',
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='notificatio_action_a8c9c6_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_7b6cc3_idx'), models.Index(fields=['ip_address', 'created_at'], name='notificatio_ip_addr_d7d988_idx'), models.Index(fields=['notification', 'created_at'], name='notificatio_notific_8029e6_idx')],
            },
        ),
    ]
