# Generated by Django 6.0.1 on 2026-01-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('reviewing', '审核中'), ('approved', '已通过'), ('rejected', '已驳回'), ('publicized', '已公示'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('application_reason', models.TextField(verbose_name='申请理由')),
                ('achievements', models.JSONField(blank=True, default=list, verbose_name='主要成果')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件列表')),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='匹配度')),
                ('match_details', models.JSONField(blank=True, default=dict, verbose_name='匹配详情')),
                ('review_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('review_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('publicize_start', models.DateTimeField(blank=True, null=True, verbose_name='公示开始时间')),
                ('publicize_end', models.DateTimeField(blank=True, null=True, verbose_name='公示结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '评奖评优申请',
                'verbose_name_plural': '评奖评优申请',
                'db_table': 'award_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AwardPublicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公示标题')),
                ('content', models.TextField(verbose_name='公示内容')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '公示记录',
                'verbose_name_plural': '公示记录',
                'db_table': 'award_publicities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AwardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='奖项名称')),
                ('category', models.CharField(choices=[('scholarship', '奖学金'), ('grant', '助学金'), ('honor', '荣誉称号')], max_length=20, verbose_name='奖项类别')),
                ('level', models.CharField(blank=True, max_length=50, verbose_name='级别')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='金额')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('criteria', models.JSONField(blank=True, default=dict, verbose_name='评选条件')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('application_start', models.DateTimeField(blank=True, null=True, verbose_name='申请开始时间')),
                ('application_end', models.DateTimeField(blank=True, null=True, verbose_name='申请结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '奖项类型',
                'verbose_name_plural': '奖项类型',
                'db_table': 'award_types',
                'ordering': ['-created_at'],
            },
        ),
    ]
