# Generated by Django 6.0.1 on 2026-01-15 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('awards', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='awardapplication',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_awards', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='awardapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_applications', to='students.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='awardpublicity',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicities', to='awards.awardapplication', verbose_name='申请'),
        ),
        migrations.AddField(
            model_name='awardapplication',
            name='award_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='awards.awardtype', verbose_name='奖项类型'),
        ),
        migrations.AlterUniqueTogether(
            name='awardapplication',
            unique_together={('student', 'award_type')},
        ),
    ]
