# Generated by Django 4.2.27 on 2026-02-27 15:20

import apps.electronic_signature.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0005_alter_role_role_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='签章名称')),
                ('signature_image', models.ImageField(upload_to=apps.electronic_signature.models.signature_image_path, verbose_name='签章图片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='rbac.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '部门签章',
                'verbose_name_plural': '部门签章',
                'db_table': 'department_signatures',
                'unique_together': {('department',)},
            },
        ),
        migrations.CreateModel(
            name='ElectronicFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='文件标题')),
                ('description', models.TextField(blank=True, verbose_name='文件描述')),
                ('file', models.FileField(upload_to=apps.electronic_signature.models.electronic_file_path, verbose_name='文件')),
                ('file_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='文件大小')),
                ('file_type', models.CharField(choices=[('document', '文档'), ('image', '图片'), ('pdf', 'PDF'), ('other', '其他')], default='other', max_length=20, verbose_name='文件类型')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='MIME类型')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='签章时间')),
                ('signature_hash', models.CharField(blank=True, max_length=256, verbose_name='签章哈希值')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('signed', '已签章'), ('sent', '已发送'), ('revoked', '已撤回')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electronic_files', to='rbac.department', verbose_name='所属部门')),
                ('signature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_files', to='electronic_signature.departmentsignature', verbose_name='使用的签章')),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_files', to=settings.AUTH_USER_MODEL, verbose_name='签章人')),
            ],
            options={
                'verbose_name': '电子文件',
                'verbose_name_plural': '电子文件',
                'db_table': 'electronic_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('upload', '上传文件'), ('sign', '签章'), ('send', '发送文件'), ('view', '查看文件'), ('verify', '验签'), ('revoke', '撤回文件'), ('delete', '删除文件'), ('download', '下载文件')], max_length=20, verbose_name='操作类型')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='详细信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_logs', to='rbac.department', verbose_name='操作部门')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='electronic_signature.electronicfile', verbose_name='文件')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '签章操作日志',
                'verbose_name_plural': '签章操作日志',
                'db_table': 'signature_operation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operation', 'created_at'], name='signature_o_operati_1f5798_idx'), models.Index(fields=['user', 'created_at'], name='signature_o_user_id_20290e_idx'), models.Index(fields=['department', 'created_at'], name='signature_o_departm_e13b43_idx'), models.Index(fields=['ip_address', 'created_at'], name='signature_o_ip_addr_f3de3b_idx')],
            },
        ),
        migrations.CreateModel(
            name='FileRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='electronic_signature.electronicfile', verbose_name='文件')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_files', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '文件接收人',
                'verbose_name_plural': '文件接收人',
                'db_table': 'file_recipients',
                'unique_together': {('file', 'recipient')},
            },
        ),
    ]
