# Generated by Django 4.2.27 on 2026-01-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.CharField(blank=True, max_length=20, verbose_name='身份证号'),
        ),
    ]
