# Generated by Django 6.0.1 on 2026-01-15 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='企业名称')),
                ('industry', models.CharField(max_length=100, verbose_name='行业')),
                ('scale', models.CharField(choices=[('small', '小型（<50人）'), ('medium', '中型（50-500人）'), ('large', '大型（500-5000人）'), ('huge', '超大型（>5000人）')], default='medium', max_length=20, verbose_name='规模')),
                ('address', models.CharField(max_length=500, verbose_name='地址')),
                ('website', models.URLField(blank=True, verbose_name='官网')),
                ('description', models.TextField(blank=True, verbose_name='企业简介')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/', verbose_name='企业Logo')),
                ('contact_person', models.CharField(max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('is_verified', models.BooleanField(default=False, verbose_name='已认证')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '企业',
                'verbose_name_plural': '企业',
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('viewed', '已查看'), ('interview', '面试中'), ('offer', '已录用'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('cover_letter', models.TextField(blank=True, verbose_name='求职信')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='查看时间')),
            ],
            options={
                'verbose_name': '职位申请',
                'verbose_name_plural': '职位申请',
                'db_table': 'job_applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='JobFair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='招聘会名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('location', models.CharField(max_length=200, verbose_name='地点')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('max_participants', models.IntegerField(default=500, verbose_name='最大参与人数')),
                ('current_participants', models.IntegerField(default=0, verbose_name='当前参与人数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '招聘会',
                'verbose_name_plural': '招聘会',
                'db_table': 'job_fairs',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='JobFairRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
            ],
            options={
                'verbose_name': '招聘会报名',
                'verbose_name_plural': '招聘会报名',
                'db_table': 'job_fair_registrations',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='职位名称')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('job_type', models.CharField(choices=[('fulltime', '全职'), ('parttime', '兼职'), ('internship', '实习')], default='fulltime', max_length=20, verbose_name='工作类型')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='最低薪资')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='最高薪资')),
                ('location', models.CharField(max_length=200, verbose_name='工作地点')),
                ('description', models.TextField(verbose_name='职位描述')),
                ('requirements', models.TextField(verbose_name='任职要求')),
                ('benefits', models.TextField(blank=True, verbose_name='福利待遇')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('views_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '招聘信息',
                'verbose_name_plural': '招聘信息',
                'db_table': 'job_postings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='简历名称')),
                ('personal_info', models.JSONField(blank=True, default=dict, verbose_name='个人信息')),
                ('education', models.JSONField(blank=True, default=list, verbose_name='教育经历')),
                ('experience', models.JSONField(blank=True, default=list, verbose_name='工作/实习经历')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='技能')),
                ('projects', models.JSONField(blank=True, default=list, verbose_name='项目经历')),
                ('awards', models.JSONField(blank=True, default=list, verbose_name='获奖情况')),
                ('self_introduction', models.TextField(blank=True, verbose_name='自我介绍')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认简历')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '简历',
                'verbose_name_plural': '简历',
                'db_table': 'resumes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(choices=[('employed', '已就业'), ('unemployed', '待就业'), ('graduate', '升学'), ('entrepreneur', '自主创业'), ('other', '其他')], max_length=20, verbose_name='就业状态')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='职位')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='薪资')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='工作地点')),
                ('employment_date', models.DateField(blank=True, null=True, verbose_name='就业日期')),
                ('source', models.CharField(blank=True, choices=[('job_fair', '招聘会'), ('online', '网络招聘'), ('recommendation', '推荐'), ('other', '其他')], max_length=20, verbose_name='就业来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='career.company', verbose_name='就业单位')),
            ],
            options={
                'verbose_name': '就业统计',
                'verbose_name_plural': '就业统计',
                'db_table': 'employment_statistics',
                'ordering': ['-created_at'],
            },
        ),
    ]
