# Generated by Django 6.0.1 on 2026-01-15 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentstatistics',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_stats', to='students.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='students.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='jobfair',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='job_fairs', to='career.company'),
        ),
        migrations.AddField(
            model_name='jobfairregistration',
            name='job_fair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='career.jobfair', verbose_name='招聘会'),
        ),
        migrations.AddField(
            model_name='jobfairregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_fair_registrations', to='students.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='career.company', verbose_name='企业'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='career.jobposting', verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='resume',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='students.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='career.resume', verbose_name='简历'),
        ),
        migrations.AlterUniqueTogether(
            name='jobfairregistration',
            unique_together={('job_fair', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'student')},
        ),
    ]
