# Generated by Django 6.0.1 on 2026-01-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='里程碑名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('due_date', models.DateField(verbose_name='截止日期')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目里程碑',
                'verbose_name_plural': '项目里程碑',
                'db_table': 'project_milestones',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ResearchAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('paper', '论文'), ('patent', '专利'), ('book', '著作'), ('award', '获奖'), ('other', '其他')], max_length=20, verbose_name='成果类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('journal', models.CharField(blank=True, max_length=200, verbose_name='期刊/出版社')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='发表/出版日期')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='卷/期')),
                ('page_range', models.CharField(blank=True, max_length=50, verbose_name='页码')),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='DOI')),
                ('file', models.FileField(blank=True, null=True, upload_to='research/achievements/', verbose_name='成果文件')),
                ('is_verified', models.BooleanField(default=False, verbose_name='已审核')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='奖励金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '科研成果',
                'verbose_name_plural': '科研成果',
                'db_table': 'research_achievements',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=100, unique=True, verbose_name='项目编号')),
                ('project_name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('project_type', models.CharField(choices=[('national', '国家级'), ('provincial', '省级'), ('municipal', '市级'), ('university', '校级'), ('enterprise', '企业合作')], max_length=20, verbose_name='项目类型')),
                ('description', models.TextField(verbose_name='项目描述')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('status', models.CharField(choices=[('declared', '已申报'), ('approved', '已立项'), ('midterm', '中期检查'), ('final', '结题验收'), ('completed', '已完成'), ('cancelled', '已取消')], default='declared', max_length=20, verbose_name='状态')),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总经费')),
                ('used_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='已使用经费')),
                ('budget_details', models.JSONField(blank=True, default=list, verbose_name='经费明细')),
                ('application_file', models.FileField(blank=True, null=True, upload_to='research/projects/', verbose_name='申报书')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '科研项目',
                'verbose_name_plural': '科研项目',
                'db_table': 'research_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='团队名称')),
                ('description', models.TextField(blank=True, verbose_name='团队简介')),
                ('shared_files', models.JSONField(blank=True, default=list, verbose_name='共享文件')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '科研团队',
                'verbose_name_plural': '科研团队',
                'db_table': 'research_teams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='会议主题')),
                ('meeting_time', models.DateTimeField(verbose_name='会议时间')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='会议地点')),
                ('minutes', models.TextField(blank=True, verbose_name='会议纪要')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '团队会议',
                'verbose_name_plural': '团队会议',
                'db_table': 'team_meetings',
                'ordering': ['-meeting_time'],
            },
        ),
        migrations.CreateModel(
            name='TeamTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '团队任务',
                'verbose_name_plural': '团队任务',
                'db_table': 'team_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
