# Generated by Django 6.0.1 on 2026-01-15 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='researchachievement',
            name='authors',
            field=models.ManyToManyField(related_name='research_achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchachievement',
            name='first_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_author_achievements', to=settings.AUTH_USER_MODEL, verbose_name='第一作者'),
        ),
        migrations.AddField(
            model_name='researchachievement',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_achievements', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principal_projects', to=settings.AUTH_USER_MODEL, verbose_name='项目负责人'),
        ),
        migrations.AddField(
            model_name='researchachievement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='research.researchproject', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='research.researchproject', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='researchteam',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_teams', to=settings.AUTH_USER_MODEL, verbose_name='团队负责人'),
        ),
        migrations.AddField(
            model_name='researchteam',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammeeting',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attended_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammeeting',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='teammeeting',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='research.researchteam', verbose_name='团队'),
        ),
        migrations.AddField(
            model_name='teamtask',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='teamtask',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='research.researchteam', verbose_name='团队'),
        ),
    ]
