# Generated by Django 6.0.1 on 2026-01-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_type', models.CharField(choices=[('student', '学生'), ('teacher', '教职工')], max_length=20, verbose_name='申请人类型')),
                ('leave_type', models.CharField(choices=[('sick', '病假'), ('personal', '事假'), ('business', '因公'), ('other', '其他')], max_length=20, verbose_name='请假类型')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('days', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='请假天数')),
                ('reason', models.TextField(verbose_name='请假原因')),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='approval/leave/', verbose_name='医院证明')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件列表')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('approval_comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('approval_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '请假申请',
                'verbose_name_plural': '请假申请',
                'db_table': 'leave_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyMembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('party', '入党申请'), ('league', '入团申请')], max_length=20, verbose_name='申请类型')),
                ('application_form', models.FileField(blank=True, null=True, upload_to='approval/party/', verbose_name='申请书')),
                ('thought_reports', models.JSONField(blank=True, default=list, verbose_name='思想汇报列表')),
                ('other_materials', models.JSONField(blank=True, default=list, verbose_name='其他材料')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('current_step', models.CharField(blank=True, max_length=50, verbose_name='当前步骤')),
                ('approval_comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('approval_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '入党/入团申请',
                'verbose_name_plural': '入党/入团申请',
                'db_table': 'party_membership_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReimbursementApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('office', '办公费'), ('travel', '差旅费'), ('research', '科研费'), ('other', '其他')], max_length=20, verbose_name='报销类别')),
                ('title', models.CharField(max_length=200, verbose_name='报销标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='报销金额')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='币种')),
                ('fund_card_number', models.CharField(blank=True, max_length=50, verbose_name='经费卡号')),
                ('fund_card_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='经费卡余额')),
                ('invoices', models.JSONField(blank=True, default=list, verbose_name='发票列表')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回'), ('cancelled', '已取消'), ('paid', '已支付')], default='pending', max_length=20, verbose_name='状态')),
                ('approval_comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('approval_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '财务报销',
                'verbose_name_plural': '财务报销',
                'db_table': 'reimbursement_applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
