# Generated by Django 4.2.27 on 2026-01-19 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approval', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReimbursementApplicationCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='已阅')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_records', to='approval.reimbursementapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_cc_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '报销抄送',
                'verbose_name_plural': '报销抄送',
                'unique_together': {('application', 'user')},
            },
        ),
        migrations.CreateModel(
            name='LeaveApplicationCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='已阅')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_records', to='approval.leaveapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_cc_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '请假抄送',
                'verbose_name_plural': '请假抄送',
                'unique_together': {('application', 'user')},
            },
        ),
    ]
