# Generated by Django 6.0.1 on 2026-01-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活动标题')),
                ('activity_type', models.CharField(choices=[('meeting', '组织生活会'), ('lesson', '党课/团课'), ('volunteer', '志愿活动'), ('other', '其他')], max_length=20, verbose_name='活动类型')),
                ('content', models.TextField(verbose_name='活动内容')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('location', models.CharField(max_length=200, verbose_name='地点')),
                ('volunteer_hours_given', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='发放志愿时长')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '党团活动',
                'verbose_name_plural': '党团活动',
                'db_table': 'party_activities',
            },
        ),
        migrations.CreateModel(
            name='PartyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='支部名称')),
                ('branch_type', models.CharField(choices=[('party', '党支部'), ('league', '团支部')], max_length=10, verbose_name='类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '支部',
                'verbose_name_plural': '支部',
                'db_table': 'party_branches',
            },
        ),
        migrations.CreateModel(
            name='PartyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('member', '团员'), ('activist', '入党积极分子'), ('probationary', '预备党员'), ('party_member', '正式党员')], max_length=20, verbose_name='政治面貌')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='入党/入团日期')),
                ('introduction_date', models.DateField(blank=True, null=True, verbose_name='确定积极分子日期')),
                ('probationary_date', models.DateField(blank=True, null=True, verbose_name='转预备党员日期')),
                ('full_member_date', models.DateField(blank=True, null=True, verbose_name='转正式党员日期')),
                ('volunteer_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='志愿服务时长')),
            ],
            options={
                'verbose_name': '党员团员信息',
                'verbose_name_plural': '党员团员信息',
                'db_table': 'party_members',
            },
        ),
    ]
