# Generated by Django 6.0.1 on 2026-01-15 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party', '0001_initial'),
        ('rbac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partyactivity',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='party_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partybranch',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='rbac.department', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='partybranch',
            name='secretary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_branches', to=settings.AUTH_USER_MODEL, verbose_name='支部书记'),
        ),
        migrations.AddField(
            model_name='partyactivity',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='party.partybranch'),
        ),
        migrations.AddField(
            model_name='partymember',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='party.partybranch'),
        ),
        migrations.AddField(
            model_name='partymember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='party_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
