# Generated by Django 6.0.1 on 2026-01-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50, unique=True, verbose_name='课程代码')),
                ('name', models.CharField(max_length=200, verbose_name='课程名称')),
                ('credit', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='学分')),
                ('hours', models.IntegerField(default=0, verbose_name='学时')),
                ('course_type', models.CharField(choices=[('required', '必修'), ('elective', '选修'), ('public', '公选')], default='required', max_length=20, verbose_name='课程类型')),
                ('description', models.TextField(blank=True, verbose_name='课程描述')),
                ('max_students', models.IntegerField(default=50, verbose_name='最大选课人数')),
                ('current_students', models.IntegerField(default=0, verbose_name='当前选课人数')),
                ('semester', models.CharField(max_length=20, verbose_name='学期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('selected', '已选'), ('dropped', '已退'), ('completed', '已完成')], default='selected', max_length=20, verbose_name='状态')),
                ('selected_at', models.DateTimeField(auto_now_add=True, verbose_name='选课时间')),
                ('dropped_at', models.DateTimeField(blank=True, null=True, verbose_name='退课时间')),
            ],
            options={
                'verbose_name': '选课记录',
                'verbose_name_plural': '选课记录',
                'db_table': 'course_selections',
                'ordering': ['-selected_at'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='成绩')),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='绩点')),
                ('grade_level', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'F')], max_length=10, verbose_name='等级')),
                ('semester', models.CharField(max_length=20, verbose_name='学期')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩',
                'db_table': 'grades',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', '在校'), ('suspended', '休学'), ('transferred', '转学'), ('graduated', '毕业'), ('dropped', '退学'), ('expelled', '开除')], default='enrolled', max_length=20, verbose_name='学籍状态')),
                ('admission_date', models.DateField(verbose_name='入学日期')),
                ('expected_graduation_date', models.DateField(blank=True, null=True, verbose_name='预计毕业日期')),
                ('actual_graduation_date', models.DateField(blank=True, null=True, verbose_name='实际毕业日期')),
                ('student_type', models.CharField(choices=[('undergraduate', '本科生'), ('graduate', '研究生'), ('doctor', '博士生')], default='undergraduate', max_length=20, verbose_name='学生类型')),
                ('enrollment_type', models.CharField(choices=[('normal', '普通'), ('art', '艺术'), ('sports', '体育'), ('autonomous', '自主招生')], default='normal', max_length=20, verbose_name='招生类型')),
                ('status_changes', models.JSONField(blank=True, default=list, verbose_name='状态变更记录')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学籍状态',
                'verbose_name_plural': '学籍状态',
                'db_table': 'student_status',
            },
        ),
    ]
