# Generated by Django 6.0.1 on 2026-01-15 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_courses', to=settings.AUTH_USER_MODEL, verbose_name='授课教师'),
        ),
        migrations.AddField(
            model_name='courseselection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='academic.course', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='courseselection',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_selections', to='students.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academic.course', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_grades', to=settings.AUTH_USER_MODEL, verbose_name='录入教师'),
        ),
        migrations.AddField(
            model_name='studentstatus',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='students.student', verbose_name='学生'),
        ),
        migrations.AlterUniqueTogether(
            name='courseselection',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'course', 'semester')},
        ),
    ]
