# Generated by Django 4.2.27 on 2026-01-19 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentstatuschange'),
        ('academic', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='签到日期')),
                ('time_slot', models.CharField(blank=True, max_length=50, verbose_name='时间段')),
                ('status', models.CharField(choices=[('present', '出勤'), ('absent', '缺勤'), ('late', '迟到'), ('early_leave', '早退'), ('excused', '请假')], default='present', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academic.course', verbose_name='课程')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '课堂签到',
                'verbose_name_plural': '课堂签到',
                'db_table': 'attendances',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('student', 'course', 'date', 'time_slot')},
            },
        ),
    ]
