# Generated by Django 4.2.27 on 2026-02-27 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_archiveviewlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0005_course_assessment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='作业标题')),
                ('description', models.TextField(verbose_name='作业描述')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('allow_late_submission', models.BooleanField(default=True, verbose_name='允许补交')),
                ('late_penalty', models.IntegerField(default=10, help_text='百分比，如10代表扣除10%', verbose_name='逾期扣分百分比')),
                ('weight_in_score', models.IntegerField(default=0, help_text='百分比，0-100', verbose_name='占平时成绩权重')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/tasks/%Y/%m/', verbose_name='作业附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academic.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程作业',
                'verbose_name_plural': '课程作业',
                'db_table': 'assignments',
                'ordering': ['-deadline'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('time_slot', models.CharField(blank=True, max_length=50, verbose_name='时间段')),
                ('check_in_code', models.CharField(blank=True, max_length=10, verbose_name='签到码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否开启')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academic.course', verbose_name='课程')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_attendance_sessions', to=settings.AUTH_USER_MODEL, verbose_name='发起教师')),
            ],
            options={
                'verbose_name': '签到会话',
                'verbose_name_plural': '签到会话',
                'db_table': 'attendance_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='academic.attendancesession', verbose_name='签到会话'),
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/submissions/%Y/%m/', verbose_name='提交附件')),
                ('content', models.TextField(blank=True, verbose_name='作业内容')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('is_late', models.BooleanField(default=False, verbose_name='是否逾期')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='得分')),
                ('feedback', models.TextField(blank=True, verbose_name='教师评语')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('graded', '已评分'), ('returned', '已退回')], default='submitted', max_length=20, verbose_name='状态')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academic.assignment', verbose_name='作业')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='students.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '作业提交',
                'verbose_name_plural': '作业提交',
                'db_table': 'assignment_submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
