# Generated by Django 6.0.1 on 2026-01-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='竞赛名称')),
                ('level', models.CharField(max_length=50, verbose_name='级别')),
                ('organizer', models.CharField(max_length=200, verbose_name='主办单位')),
                ('registration_deadline', models.DateTimeField(verbose_name='报名截止时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否开启')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学科竞赛',
                'verbose_name_plural': '学科竞赛',
                'db_table': 'competitions',
            },
        ),
        migrations.CreateModel(
            name='CompetitionTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200, verbose_name='团队名称')),
                ('work_file', models.FileField(blank=True, null=True, upload_to='activities/competition/works/', verbose_name='参赛作品')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='评分')),
                ('award_level', models.CharField(blank=True, max_length=50, verbose_name='获奖等级')),
                ('status', models.CharField(default='registered', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '竞赛报名',
                'verbose_name_plural': '竞赛报名',
                'db_table': 'competition_teams',
            },
        ),
        migrations.CreateModel(
            name='DynamicActivityInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, verbose_name='活动数据')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '自定义活动数据',
                'verbose_name_plural': '自定义活动数据',
                'db_table': 'dynamic_activity_instances',
            },
        ),
        migrations.CreateModel(
            name='DynamicActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='活动名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='活动编码')),
                ('schema', models.JSONField(default=dict, verbose_name='表单结构定义')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '自定义活动类型',
                'verbose_name_plural': '自定义活动类型',
                'db_table': 'dynamic_activity_types',
            },
        ),
        migrations.CreateModel(
            name='SocialPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活动标题')),
                ('practice_type', models.CharField(max_length=50, verbose_name='实践类型')),
                ('team_name', models.CharField(blank=True, max_length=200, verbose_name='团队名称')),
                ('description', models.TextField(verbose_name='活动简介')),
                ('status', models.CharField(choices=[('declared', '已申报'), ('approved', '已立项'), ('submitted', '成果提交'), ('completed', '已结项'), ('excellent', '评优')], default='declared', max_length=20, verbose_name='状态')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='activities/practice/reports/', verbose_name='活动报告')),
                ('media_files', models.JSONField(blank=True, default=list, verbose_name='媒体材料')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '社会实践',
                'verbose_name_plural': '社会实践',
                'db_table': 'social_practices',
            },
        ),
    ]
