# Generated by Django 6.0.1 on 2026-01-15 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionteam',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_teams', to=settings.AUTH_USER_MODEL, verbose_name='指导教师'),
        ),
        migrations.AddField(
            model_name='competitionteam',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='activities.competition'),
        ),
        migrations.AddField(
            model_name='competitionteam',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_competition_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competitionteam',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='competition_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dynamicactivityinstance',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='dynamicactivityinstance',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='activities.dynamicactivitytype'),
        ),
        migrations.AddField(
            model_name='socialpractice',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_practices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialpractice',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='participated_practices', to=settings.AUTH_USER_MODEL),
        ),
    ]
